.TH GSH 1 "08 May 2012" "0.1" "gsh man page"

.SH NAME
gsh - gsh stands for "grid shell". It is a wrapper around globus-job-run 
commands that fakes a command line console for a remote globus gatekeeper.

.SH SYNOPSIS
.B gsh
[options] [Site FQDN]

.SH DESCRIPTION
gsh is a wrapper around globus-job-run commands that fakes a command line 
console for a remote globus gatekeeper.

.SH OPTIONS

.B "-h, --help"
    show this help message and exit

.B "-v, --version"
    Report the version of gsh and exit

.SH AUTHOR
Written by Anthony Tiradani

.SH "REPORTING BUGS"
Report gsh bugs to https://ticket.grid.iu.edu/goc/submit

.SH COPYRIGHT

Fermilab Software Legal Information (BSD License)
Copyright (c) 2012, FERMI NATIONAL ACCELERATOR LABORATORY
All rights reserved.
