.TH GRIDSH 1 "08 May 2012" "0.1" "gridsh man page"

.SH NAME
gridsh - ggridsh stands for "grid shell". It is a wrapper around globus-job-run 
commands that fakes a command line console for a remote globus gatekeeper.

.SH SYNOPSIS
.B gridsh
[options] [Site FQDN]

.SH DESCRIPTION
gridsh is a wrapper around globus-job-run commands that fakes a command line 
console for a remote globus gatekeeper.

.SH OPTIONS

.B "-h, --help"
    show this help message and exit

.B "-v, --version"
    Report the version of gridsh and exit

.SH AUTHOR
Written by Anthony Tiradani

.SH "REPORTING BUGS"
Report gridsh bugs to https://ticket.grid.iu.edu/goc/submit

.SH COPYRIGHT

Fermilab Software Legal Information (BSD License)
Copyright (c) 2012, FERMI NATIONAL ACCELERATOR LABORATORY
All rights reserved.
